#!/bin/bash

DEST="/usr/bin/punish"
SUDOERS_FILE="/etc/sudoers.d/epitroll"

echo "Configuring password-less execution for EpiTroll..."
echo "ALL ALL=(ALL) NOPASSWD: $DEST" > "$SUDOERS_FILE"
chmod 0440 "$SUDOERS_FILE"

echo "EpiTroll installed! Usage: sudo punish [FLAGS]"
